//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    
    public enum CodigoTipoUsuario : int
    {
        UsuarioFinal = 1,
        AdministradorSupermercado = 2,
        AdminstradorSistema = 3
    }
}
