//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaListaCompraItem
    {
        public int IdListaCompra { get; set; }
        public int IdMercado { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int IdProduto { get; set; }
        public bool Disponivel { get; set; }
        public Nullable<double> Quantidade { get; set; }
        public Nullable<double> ValorProduto { get; set; }
    
        public virtual ConsultaListaCompra ConsultaListaCompra { get; set; }
        public virtual ListaCompraItem ListaCompraItem { get; set; }
    }
}
