//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCompraItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaCompraItem()
        {
            this.ListaConsultaListaCompraItem = new HashSet<ConsultaListaCompraItem>();
        }
    
        public int IdListaCompra { get; set; }
        public int IdProduto { get; set; }
        public double Quantidade { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAlteracao { get; set; }
        public Nullable<System.DateTime> DataDelecao { get; set; }
        public bool Deletado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultaListaCompraItem> ListaConsultaListaCompraItem { get; set; }
        public virtual ListaCompra ListaCompra { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
