//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.ListaSupermercadoProduto = new HashSet<SupermercadoProduto>();
            this.ListaCompraItem = new HashSet<ListaCompraItem>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<double> PesoMedio { get; set; }
        public Nullable<double> PesoMaximo { get; set; }
        public Nullable<double> PesoMinimo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupermercadoProduto> ListaSupermercadoProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaCompraItem> ListaCompraItem { get; set; }
    }
}
