//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFIDProduto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFIDProduto()
        {
            this.ItemVenda = new HashSet<ItemVenda>();
        }
    
        public int IdMercado { get; set; }
        public int IdProduto { get; set; }
        public long RFIDSerial { get; set; }
        public System.DateTime DataEmisao { get; set; }
        public Nullable<System.DateTime> DataConsumo { get; set; }
        public Nullable<System.DateTime> DataUltimaLeitura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemVenda> ItemVenda { get; set; }
        public virtual SupermercadoProduto SupermercadoProduto { get; set; }
    }
}
