//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecaoProduto
    {
        public int IdSecao { get; set; }
        public int IdMercado { get; set; }
        public int IdProduto { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Secao Secao { get; set; }
        public virtual SupermercadoProduto ListaSupermercadoProduto { get; set; }
    }
}
