//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartMarketModelContainer : DbContext
    {
        public SmartMarketModelContainer()
            : base("name=SmartMarketModelContainer")
        {
    		base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> ClienteSet { get; set; }
        public virtual DbSet<ItemVenda> ItemVendaSet { get; set; }
        public virtual DbSet<Produto> ProdutoSet { get; set; }
        public virtual DbSet<RFIDProduto> RFIDProdutoSet { get; set; }
        public virtual DbSet<Secao> SecaoSet { get; set; }
        public virtual DbSet<SecaoProduto> SecaoProdutoSet { get; set; }
        public virtual DbSet<Supermercado> SupermercadoSet { get; set; }
        public virtual DbSet<SupermercadoProduto> SupermercadoProdutoSet { get; set; }
        public virtual DbSet<Venda> VendaSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<ConsultaListaCompra> TB_CONSULTA_LISTA_COMPRA { get; set; }
        public virtual DbSet<ConsultaListaCompraItem> TB_CONSULTA_LISTA_COMPRA_ITEM { get; set; }
        public virtual DbSet<ListaCompra> TB_LISTA_COMPRA { get; set; }
        public virtual DbSet<ListaCompraItem> TB_LISTA_COMPRA_ITEM { get; set; }
        public virtual DbSet<TipoUsuario> TB_TIPO_USUARIO { get; set; }
    }
}
