//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSC.SmartMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupermercadoProduto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupermercadoProduto()
        {
            this.ListaItemVenda = new HashSet<ItemVenda>();
            this.ListaRFIDProduto = new HashSet<RFIDProduto>();
            this.ListaSecaoProduto = new HashSet<SecaoProduto>();
        }
    
        public int IdMercado { get; set; }
        public int IdProduto { get; set; }
        public double ValorProduto { get; set; }
        public double QuantidadeEstoque { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemVenda> ListaItemVenda { get; set; }
        public virtual Produto Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFIDProduto> ListaRFIDProduto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecaoProduto> ListaSecaoProduto { get; set; }
        public virtual Supermercado Supermercado { get; set; }
    }
}
