IF NOT EXISTS(SELECT TOP 1 1 FROM [dbo].[TB_TIPO_USUARIO] WHERE [ID_TIPO_USUARIO] = 1)
	INSERT INTO [dbo].[TB_TIPO_USUARIO] ([ID_TIPO_USUARIO], [DS_TIPO_USUARIO]) VALUES (1, 'Usuário Final');
IF NOT EXISTS(SELECT TOP 1 1 FROM [dbo].[TB_TIPO_USUARIO] WHERE [ID_TIPO_USUARIO] = 2)
	INSERT INTO [dbo].[TB_TIPO_USUARIO] ([ID_TIPO_USUARIO], [DS_TIPO_USUARIO]) VALUES (2, 'Administrador de Supermercado');
IF NOT EXISTS(SELECT TOP 1 1 FROM [dbo].[TB_TIPO_USUARIO] WHERE [ID_TIPO_USUARIO] = 3)
	INSERT INTO [dbo].[TB_TIPO_USUARIO] ([ID_TIPO_USUARIO], [DS_TIPO_USUARIO]) VALUES (3, 'Administrador do Sistema');