CREATE TABLE [dbo].[TB_RFID_PRODUTO] (
     [ID_MERCADO] INT NOT NULL
    ,[ID_PRODUTO] INT NOT NULL
    ,[ID_SERIAL] BIGINT NOT NULL
    ,[DT_EMISSAO] DATETIME NOT NULL
    ,[DT_CONSUMO] DATETIME NULL
    ,[DT_ULT_LEITURA] DATETIME NULL
    ,CONSTRAINT [PK_RFID_PRODUTO]
		PRIMARY KEY CLUSTERED
		(
			 [ID_MERCADO] ASC
			,[ID_PRODUTO] ASC
			,[ID_SERIAL] ASC
		)
    ,CONSTRAINT [FK_RFID_PROD_SUPERMERC_PROD]
		FOREIGN KEY
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
		REFERENCES [dbo].[TB_SUPERMERCADO_PRODUTO]
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
);

