CREATE TABLE [dbo].[TB_LISTA_COMPRA_ITEM]
(
	 [ID_LISTA_COMPRA] INT NOT NULL
	,[ID_PRODUTO] INT NOT NULL
	,[QT_ITEM] FLOAT (53) NOT NULL
	,[DT_CRIACAO] DATETIME NOT NULL
	,[DT_ALTERACAO] DATETIME NOT NULL
	,[DT_DELECAO] DATETIME NULL
	,[IN_DELETADO] BIT NOT NULL DEFAULT 0
	,CONSTRAINT [PK_LISTA_COMPRA_ITEM]
		PRIMARY KEY CLUSTERED
		(
			 [ID_LISTA_COMPRA]
			,[ID_PRODUTO]
		)
	,CONSTRAINT [FK_LISTA_COMPRA_ITEM_LISTA_COMPRA]
		FOREIGN KEY
		(
			[ID_LISTA_COMPRA]
		)
		REFERENCES [dbo].[TB_LISTA_COMPRA]
		(
			[ID_LISTA_COMPRA]
		)
	,CONSTRAINT [FK_LISTA_COMPRA_ITEM_PRODUTO]
		FOREIGN KEY
		(
			[ID_PRODUTO]
		)
		REFERENCES [dbo].[TB_PRODUTO]
		(
			[ID_PRODUTO]
		)
	,CONSTRAINT [CK_LISTA_COMPRA_ITEM_QT_ITEM]
		CHECK ([QT_ITEM] > 0)
	,CONSTRAINT [CK_LISTA_COMPRA_ITEM_DT_DELECAO]
		CHECK (([IN_DELETADO] = 0 AND [DT_DELECAO] IS NULL) OR ([IN_DELETADO] = 1 AND [DT_DELECAO] IS NOT NULL))
)
