CREATE TABLE [dbo].[TB_SECAO] (
     [ID_SECAO] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL
    ,[ID_MERCADO] INT NOT NULL
    ,[NM_SECAO] NVARCHAR (100) NOT NULL
    ,CONSTRAINT [PK_SECAO]
		PRIMARY KEY CLUSTERED
		(
			 [ID_SECAO] ASC
			,[ID_MERCADO] ASC
		)
    ,CONSTRAINT [FK_SECAO_SUPERMERCADO]
		FOREIGN KEY
		(
			[ID_MERCADO]
		)
		REFERENCES [dbo].[TB_SUPERMERCADO]
		(
			[ID_MERCADO]
		)
);

