CREATE TABLE [dbo].[TB_USUARIO] (
     [ID_USUARIO] INT IDENTITY (1, 1) NOT NULL
    ,[NM_USUARIO] NVARCHAR (100) NULL
    ,[DS_EMAIL] NVARCHAR (255) NULL
    ,[IN_ATIVO] BIT DEFAULT (1) NULL
    ,[DT_CADASTRO] DATETIME DEFAULT (GETDATE()) NULL
    ,[DT_ALTERACAO] DATETIME DEFAULT (GETDATE()) NULL
    ,[IN_DELETADO] BIT DEFAULT (0) NULL
    ,[DS_SENHA] NVARCHAR (50) NULL
	,[ID_TIPO_USUARIO] INT NOT NULL
	,[ID_CLIENTE] INT NULL
    ,CONSTRAINT [PK_USUARIO]
		PRIMARY KEY CLUSTERED
		(
			 [ID_USUARIO] ASC
		)
    ,CONSTRAINT [UN_USUAIRO_EMAIL]
		UNIQUE NONCLUSTERED
		(
			 [DS_EMAIL] ASC
		)
    ,CONSTRAINT [UN_USUARIO_NOME]
		UNIQUE NONCLUSTERED
		(
			 [NM_USUARIO] ASC
		)
	,CONSTRAINT [FK_TIPO_USUARIO]
		FOREIGN KEY
		(
			 [ID_TIPO_USUARIO]
		) REFERENCES [dbo].[TB_TIPO_USUARIO]
		(
			 [ID_TIPO_USUARIO]
		)
	,CONSTRAINT [FK_USUARIO_CLIENTE]
		FOREIGN KEY
		(
			 [ID_CLIENTE]
		)
		REFERENCES [dbo].[TB_CLIENTE]
		(
			 [ID_CLIENTE]
		)
	,CONSTRAINT [CK_USUARIO_CLIENTE]
		CHECK
		(
			(([ID_TIPO_USUARIO] != 1) AND ([ID_CLIENTE] IS NULL))
			OR
			(([ID_TIPO_USUARIO] = 1) AND ([ID_CLIENTE] IS NOT NULL))
		)
);

