CREATE TABLE [dbo].[TB_SECAO_PRODUTO] (
     [ID_SECAO] INT NOT NULL
    ,[ID_MERCADO] INT NOT NULL
    ,[ID_PRODUTO] INT NOT NULL
    ,[IN_ATIVO] BIT DEFAULT ((1)) NOT NULL
    ,CONSTRAINT [PK_SECAO_PRODUTO]
		PRIMARY KEY CLUSTERED
		(
			 [ID_PRODUTO] ASC
			,[ID_SECAO] ASC
			,[ID_MERCADO] ASC
		)
    ,CONSTRAINT [FK_SECAO_PROD_SUPERMERC_PROD]
		FOREIGN KEY
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
		REFERENCES [dbo].[TB_SUPERMERCADO_PRODUTO]
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
    ,CONSTRAINT [FK_SECAO_PROUTO_SECAO]
		FOREIGN KEY
		(
			 [ID_SECAO]
			,[ID_MERCADO]
		)
		REFERENCES [dbo].[TB_SECAO]
		(
			 [ID_SECAO]
			,[ID_MERCADO]
		)
);

