CREATE TABLE [dbo].[TB_ITEM_VENDA] (
     [ID_VENDA]   INT        NOT NULL
    ,[NR_ITEM]    INT        NOT NULL
    ,[ID_MERCADO] INT        NOT NULL
    ,[ID_PRODUTO] INT        NOT NULL
    ,[VL_PRODUTO] FLOAT (53) NOT NULL
    ,[ID_SERIAL]  BIGINT     NULL
    ,CONSTRAINT [PK_ITEM_VENDA]
		PRIMARY KEY CLUSTERED
		(
			 [ID_MERCADO] ASC
			,[ID_PRODUTO] ASC
			,[ID_VENDA] ASC
			,[NR_ITEM] ASC
		)
    ,CONSTRAINT [FK_ITEM_VENDA_RFID_PRODUTO]
		FOREIGN KEY
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
			,[ID_SERIAL]
		)
		REFERENCES [dbo].[TB_RFID_PRODUTO]
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
			,[ID_SERIAL]
		)
    ,CONSTRAINT [FK_ITEM_VENDA_SUPERMERC_PROD]
		FOREIGN KEY
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
		REFERENCES [dbo].[TB_SUPERMERCADO_PRODUTO]
		(
			 [ID_MERCADO]
			,[ID_PRODUTO]
		)
    ,CONSTRAINT [FK_ITEM_VENDA_VENDA]
		FOREIGN KEY
		(
			[ID_VENDA]
		)
		REFERENCES [dbo].[TB_VENDA]
		(
			[ID_VENDA]
		)
);

