CREATE TABLE [dbo].[TB_SUPERMERCADO_PRODUTO] (
    [ID_MERCADO] INT        NOT NULL,
    [ID_PRODUTO] INT        NOT NULL,
    [VL_PRODUTO] FLOAT (53) NOT NULL,
    [QT_ESTOQUE] FLOAT (53) NOT NULL,
    CONSTRAINT [PK_SUPERMERCADO_PRODUTO] PRIMARY KEY CLUSTERED ([ID_MERCADO] ASC, [ID_PRODUTO] ASC),
    CONSTRAINT [FK_SUPERMERC_PROD_SUPERMERC] FOREIGN KEY ([ID_MERCADO]) REFERENCES [dbo].[TB_SUPERMERCADO] ([ID_MERCADO]),
    CONSTRAINT [FK_SUPERMERCADO_PRODUTO_PROD] FOREIGN KEY ([ID_PRODUTO]) REFERENCES [dbo].[TB_PRODUTO] ([ID_PRODUTO])
);

