CREATE TABLE [dbo].[TB_SUPERMERCADO] (
     [ID_MERCADO] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL
    ,[NM_MERCADO] NVARCHAR (100) NOT NULL
	,[ID_GEOCODE] NVARCHAR(100) NULL
    ,CONSTRAINT [PK_SUPERMERCADO]
		PRIMARY KEY CLUSTERED
		(
			 [ID_MERCADO] ASC
		)
);

