CREATE TABLE [dbo].[TB_VENDA] (
    [ID_VENDA]   INT      IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ID_CLIENTE] INT      NOT NULL,
    [DT_VENDA]   DATETIME NULL,
    [ID_MERCADO] INT      NOT NULL,
    CONSTRAINT [PK_VENDA] PRIMARY KEY CLUSTERED ([ID_VENDA] ASC),
    CONSTRAINT [FK_VENDA_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[TB_CLIENTE] ([ID_CLIENTE]),
    CONSTRAINT [FK_VENDA_SUPERMERCADO] FOREIGN KEY ([ID_MERCADO]) REFERENCES [dbo].[TB_SUPERMERCADO] ([ID_MERCADO])
);

