CREATE TABLE [dbo].[TB_PRODUTO] (
     [ID_PRODUTO] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL
    ,[NM_PRODUTO] NVARCHAR (100) NOT NULL
    ,[VL_PESO_MEDIO] FLOAT (53) NULL
    ,[VL_PESO_MAX] FLOAT (53) NULL
    ,[VL_PESO_MIN] FLOAT (53) NULL
    ,CONSTRAINT [PK_PRODUTO]
		PRIMARY KEY CLUSTERED
		(
			[ID_PRODUTO] ASC
		)
);

